import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-icon-picker-dialog',
  standalone: false,
  templateUrl: './icon-picker-dialog.html',
  styleUrl: './icon-picker-dialog.scss',
})
export class IconPickerDialog {
  @Output() iconSelected = new EventEmitter<string>();
  visible: boolean = false;

  // A list of common PrimeNG icons. You can extend this list.
  rawPrimeNgIcons: string[] = [
    'pi-wifi',
    'pi-arrow-circle-right',
    'pi-apple',
    'pi-th-large',
    'pi-server',
    // 'pi-coffee',
    'pi-cog',
    'pi-lock',
    'pi-home',
    'pi-phone',
    'pi-ellipsis-h',
    'pi-user',
    'pi-cloud',
    'pi-desktop',
    'pi-bell',
    'pi-lightbulb',
    'pi-camera',
    'pi-file',
    'pi-folder',
    'pi-check',
    // 'pi-flask',
    'pi-briefcase',
    'pi-comments',
    'pi-external-link',
    'pi-chart-bar',
    // 'pi-headset',
    'pi-eye',
    'pi-bolt',
    'pi-car',
    'pi-map-marker',
    'pi-globe',
    'pi-wallet',
    'pi-credit-card',
    'pi-shopping-cart',
    'pi-box',
    'pi-tag',
    'pi-ticket',
    'pi-truck',
    'pi-star',
    'pi-heart',
    'pi-calendar',
    'pi-dollar',
    'pi-euro',
    'pi-align-left',
    'pi-align-center',
    'pi-align-right',
    'pi-align-justify',
    'pi-link',
    // 'pi-unlink',
    'pi-plus',
    'pi-minus',
    'pi-times',
    'pi-check-circle',
    'pi-times-circle',
    'pi-info-circle',
    'pi-exclamation-triangle',
    'pi-question-circle',
    'pi-sort',
    'pi-sort-alt',
    'pi-sort-alpha-down',
    'pi-sort-alpha-up',
    'pi-sort-amount-down',
    'pi-sort-amount-up',
    'pi-sort-numeric-down',
    'pi-sort-numeric-up',
    'pi-arrow-down',
    'pi-arrow-up',
    'pi-arrow-left',
    'pi-arrow-right',
    'pi-angle-down',
    'pi-angle-up',
    'pi-angle-left',
    'pi-angle-right',
    'pi-arrows-v',
    'pi-arrows-h',
    'pi-refresh',
    'pi-download',
    'pi-upload',
    'pi-print',
    'pi-search',
    'pi-filter',
    'pi-trash',
    'pi-undo',
    // 'pi-redo',
    'pi-sync',
    'pi-sign-in',
    'pi-sign-out',
    'pi-pencil',
    'pi-plus-circle',
    'pi-minus-circle',
    'pi-clone',
    'pi-copy',
    // 'pi-paste',
    // 'pi-cut',
    'pi-bookmark',
    'pi-chart-line',
    'pi-list',
    'pi-sliders-h',
    'pi-ellipsis-v',
    'pi-bars',
    // 'pi-grip-vertical',
    // 'pi-grid',
    'pi-table',
    'pi-sitemap',
    'pi-directions',
    'pi-map',
    'pi-inbox',
    'pi-envelope',
    'pi-send',
    'pi-share-alt',
    'pi-volume-up',
    'pi-volume-down',
    'pi-volume-off',
    'pi-step-backward',
    'pi-fast-backward',
    'pi-backward',
    'pi-play',
    'pi-pause',
    'pi-stop',
    'pi-forward',
    'pi-fast-forward',
    'pi-step-forward',
    'pi-eject',
    'pi-tablet',
    'pi-mobile',
    'pi-compass',
    'pi-sun',
    'pi-moon',
    'pi-star-fill',
    'pi-heart-fill',
    'pi-bookmark-fill',
    'pi-power-off',
    'pi-qrcode',
    'pi-code',
    // 'pi-bug',
    // 'pi-terminal',
    'pi-database',
    'pi-cloud-upload',
    'pi-cloud-download',
    'pi-key',
    'pi-shield',
    // 'pi-bus',
    // 'pi-train',
    // 'pi-plane',
    // 'pi-ship',
    // 'pi-bicycle',
    // 'pi-motorcycle',
    // 'pi-walk',
    // 'pi-running',
    'pi-shopping-bag',
    'pi-gift',
    'pi-chart-pie',
    // 'pi-chart-doughnut',
    'pi-gauge',
    'pi-calendar-plus',
    'pi-calendar-minus',
    'pi-calendar-times',
    // 'pi-calendar-check',
    'pi-building',
    // 'pi-city',
    // 'pi-industry',
    'pi-palette',
    // 'pi-fill',
    'pi-eye-slash',
    'pi-angle-double-down',
    'pi-angle-double-up',
    'pi-angle-double-left',
    'pi-angle-double-right',
    'pi-filter-fill',
    // 'pi-th-large-fill',
    // 'pi-cog-fill',
    // 'pi-map-marker-fill',
    // 'pi-credit-card-fill',
    // 'pi-shopping-cart-fill',
    // 'pi-wallet-fill',
    // 'pi-bell-fill',
    // 'pi-calendar-plus-fill',
    // 'pi-calendar-minus-fill',
    // 'pi-calendar-times-fill',
    // 'pi-calendar-check-fill',
    // 'pi-check-circle-fill',
    // 'pi-times-circle-fill',
    // 'pi-info-circle-fill',
    // 'pi-exclamation-triangle-fill',
    // 'pi-question-circle-fill',
    // 'pi-user-fill',
    // 'pi-home-fill',
    // 'pi-lock-fill',
    // 'pi-phone-fill',
    // 'pi-cloud-fill',
    // 'pi-desktop-fill',
    // 'pi-lightbulb-fill',
    // 'pi-camera-fill',
    // 'pi-file-fill',
    // 'pi-folder-fill',
    // 'pi-briefcase-fill',
    // 'pi-comments-fill',
    // 'pi-inbox-fill',
    // 'pi-envelope-fill',
    // 'pi-send-fill',
    // 'pi-share-alt-fill',
    // 'pi-volume-up-fill',
    // 'pi-volume-down-fill',
    // 'pi-volume-off-fill',
    // 'pi-play-fill',
    // 'pi-pause-fill',
    // 'pi-stop-fill',
    // 'pi-forward-fill',
    // 'pi-backward-fill',
    // 'pi-refresh-fill',
    // 'pi-download-fill',
    // 'pi-upload-fill',
    // 'pi-print-fill',
    // 'pi-search-fill',
    'pi-filter-fill',
    // 'pi-trash-fill',
    // 'pi-undo-fill',
    // 'pi-redo-fill',
    // 'pi-sync-fill',
    // 'pi-sign-in-fill',
    // 'pi-sign-out-fill',
    // 'pi-pencil-fill',
    // 'pi-plus-circle-fill',
    // 'pi-minus-circle-fill',
    // 'pi-clone-fill',
    // 'pi-copy-fill',
    // 'pi-paste-fill',
    // 'pi-cut-fill',
    'pi-check-square',
    // 'pi-square',
    'pi-circle',
    'pi-circle-fill',
    // 'pi-square-fill',
    'pi-info',
    // 'pi-exclamation',
    'pi-question',
    'pi-ban',
    'pi-reply',
    'pi-comment',
    'pi-barcode',
    // 'pi-rss',
    'pi-image',
    'pi-video',
    'pi-microphone',
    'pi-wrench',
    'pi-hammer',
    // 'pi-umbrella',
    'pi-users',
    'pi-id-card',
    'pi-address-book',
    'pi-clock',
    'pi-history',
    'pi-pound',
    // 'pi-yen',
    'pi-bitcoin',
    'pi-ethereum',
    // 'pi-bank',
    // 'pi-puzzle-piece',
    'pi-unlock',
    'pi-exclamation-circle',
    // 'pi-maximize',
    // 'pi-minimize',
    'pi-search-plus',
    'pi-search-minus',
    // 'pi-zoom-in',
    // 'pi-zoom-out',
    'pi-images',
    'pi-folder-open',
    'pi-paperclip',
    // 'pi-bold',
    // 'pi-italic',
    // 'pi-underline',
    // 'pi-strike',
    // 'pi-indent',
    // 'pi-outdent',
    // 'pi-list-ol',
    // 'pi-list-ul',
    // 'pi-quote-left',
    // 'pi-quote-right',
    'pi-save',
    // 'pi-compress',
    'pi-expand',
    // 'pi-brush',
    'pi-eraser',
    // 'pi-ruler',
    // 'pi-tree',
    // 'pi-leaf',
    'pi-trophy',
    'pi-money-bill',
    // 'pi-music',
    // 'pi-grip-horizontal',
    'pi-spinner',
  ];

  filteredPrimeNgIcons: string[] = []; // Esta lista será usada no template

  constructor() {}

  ngOnInit() {
    this.filterIcons();
  }

  private filterIcons(): void {
    this.filteredPrimeNgIcons = this.rawPrimeNgIcons.filter(
      (icon) => icon !== null && icon !== undefined && icon.trim() !== ''
    );
  }

  show() {
    this.visible = true;
  }

  hide() {
    this.visible = false;
  }

  selectIcon(icon: string) {
    this.iconSelected.emit(icon);
    this.hide();
  }

  cancelSelection() {
    this.hide();
  }
}
