import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-icon-picker-dialog',
  standalone: false,
  templateUrl: './icon-picker-dialog.html',
  styleUrl: './icon-picker-dialog.scss',
})
export class IconPickerDialog {
  @Output() iconSelected = new EventEmitter<string>();
  visible: boolean = false;

  rawPrimeNgIcons: string[] = [
    'pi-phone',
    'pi-wallet',
    'pi-credit-card',
    'pi-shopping-cart',
    'pi-car',
    'pi-home',
    'pi-receipt',
    'pi-barcode',
    'pi-shopping-bag',
    'pi-gift',
    'pi-money-bill',
    'pi-dollar',
    'pi-graduation-cap',
    'pi-wifi',

    'pi-user',
    'pi-users',
    'pi-desktop',
    'pi-bell',
    'pi-camera',
    'pi-ticket',
    'pi-calendar',
    'pi-briefcase',
    'pi-shop',
    'pi-cart-arrow-down',
    'pi-qrcode',
    'pi-calendar-plus',
    'pi-calendar-minus',
    'pi-building',

    'pi-truck',
    'pi-gauge',
    'pi-tag',
    'pi-map-marker',
    'pi-video',
    'pi-microphone',
    'pi-headphones',
    'pi-sparkles',
    'pi-pencil',
    'pi-crown',
    'pi-star',
    'pi-star-fill',
    'pi-heart',
    'pi-heart-fill',

    'pi-bookmark-fill',
    'pi-file-pdf',
    'pi-trophy',
    'pi-objects-column',
    'pi-eye',
    'pi-bolt',
    'pi-box',
    'pi-trash',
    'pi-chart-bar',
    'pi-link',
    'pi-paperclip',
    'pi-cloud',
    'pi-lock',
    'pi-lightbulb',

    'pi-file',
    'pi-folder',
    'pi-check',
    'pi-comments',
    'pi-external-link',
    'pi-globe',
    'pi-euro',
    'pi-refresh',
    'pi-download',
    'pi-upload',
    'pi-print',
    'pi-search',
    'pi-plus-circle',
    'pi-minus-circle',

    'pi-chart-line',
    'pi-inbox',
    'pi-envelope',
    'pi-send',
    'pi-volume-up',
    'pi-play',
    'pi-compass',
    'pi-sun',
    'pi-moon',
    'pi-power-off',
    'pi-code',
    'pi-database',
    'pi-key',
    'pi-palette',

    'pi-check-square',
    'pi-comment',
    'pi-image',
    'pi-wrench',
    'pi-hammer',
    'pi-id-card',
    'pi-address-book',
    'pi-clock',
    'pi-unlock',
    'pi-images',
    'pi-save',
    'pi-at',
    'pi-book',
    'pi-calculator',

    'pi-info-circle',
    'pi-exclamation-triangle',
    'pi-question-circle',
    'pi-sort',
    'pi-sort-alt',
    'pi-asterisk',
    'pi-question',
    'pi-ban',
    'pi-plus',
    'pi-minus',
    'pi-times',
    'pi-check-circle',
    'pi-times-circle',
    'pi-chevron-down',
    'pi-chevron-left',
    'pi-chevron-right',
    'pi-chevron-up',

    'pi-apple',
    'pi-amazon',
    'pi-android',
    'pi-bitcoin',
    'pi-ethereum',
    'pi-discord',
    'pi-facebook',
    'pi-github',
    'pi-google',
    'pi-instagram',
    'pi-linkedin',
    'pi-paypal',
    'pi-twitch',
    'pi-twitter',
    'pi-vimeo',
    'pi-whatsapp',
    'pi-youtube',

    // 'pi-filter',

    // 'pi-arrow-circle-right',
    // 'pi-th-large',
    // 'pi-server',
    // 'pi-cog',
    // 'pi-ellipsis-h',
    // 'pi-align-left',
    // 'pi-align-center',
    // 'pi-align-right',
    // 'pi-align-justify',
    // 'pi-sort-alpha-down',
    // 'pi-sort-alpha-up',
    // 'pi-sort-amount-down',
    // 'pi-sort-amount-up',
    // 'pi-sort-numeric-down',
    // 'pi-sort-numeric-up',
    // 'pi-arrow-down',
    // 'pi-arrow-up',
    // 'pi-arrow-left',
    // 'pi-arrow-right',
    // 'pi-angle-down',
    // 'pi-angle-up',
    // 'pi-angle-left',
    // 'pi-angle-right',
    // 'pi-arrows-v',
    // 'pi-arrows-h',
    // 'pi-undo',
    // 'pi-sync',
    // 'pi-sign-in',
    // 'pi-sign-out',
    // 'pi-clone',
    // 'pi-copy',
    // 'pi-bookmark',
    // 'pi-list',
    // 'pi-sliders-h',
    // 'pi-ellipsis-v',
    // 'pi-bars',
    // 'pi-table',
    // 'pi-sitemap',
    // 'pi-directions',
    // 'pi-map',
    // 'pi-share-alt',
    // 'pi-volume-down',
    // 'pi-volume-off',
    // 'pi-step-backward',
    // 'pi-fast-backward',
    // 'pi-backward',
    // 'pi-pause',
    // 'pi-stop',
    // 'pi-forward',
    // 'pi-fast-forward',
    // 'pi-step-forward',
    // 'pi-eject',
    // 'pi-tablet',
    // 'pi-mobile',
    // 'pi-cloud-upload',
    // 'pi-cloud-download',
    // 'pi-shield',
    // 'pi-chart-pie',
    // 'pi-calendar-times',
    // 'pi-eye-slash',
    // 'pi-angle-double-down',
    // 'pi-angle-double-up',
    // 'pi-angle-double-left',
    // 'pi-angle-double-right',
    // 'pi-filter-fill',
    // 'pi-circle',
    // 'pi-circle-fill',
    // 'pi-info',
    // 'pi-reply',
    // 'pi-history',
    // 'pi-pound',
    // 'pi-exclamation-circle',
    // 'pi-search-plus',
    // 'pi-search-minus',
    // 'pi-folder-open',
    // 'pi-expand',
    // 'pi-eraser',
    // 'pi-spinner',
    // 'pi-arrow-circle-down',
    // 'pi-arrow-circle-left',
    // 'pi-arrow-circle-up',
    // 'pi-arrow-down-left',
    // 'pi-arrow-down-left-and-arrow-up-right-to-center',
    // 'pi-arrow-down-right',
    // 'pi-arrow-up-left',
    // 'pi-arrow-up-right',
    // 'pi-arrow-up-right-and-arrow-down-left-from-center',
    // 'pi-arrows-alt',
    // 'pi-bell-slash',
    // 'pi-building-columns',
    // 'pi-bullseye',
    // 'pi-calendar-clock',
    // 'pi-caret-down',
    // 'pi-caret-left',
    // 'pi-caret-right',
    // 'pi-caret-up',
    // 'pi-cart-minus',
    // 'pi-cart-plus',
    // 'pi-chevron-circle-down',
    // 'pi-chevron-circle-left',
    // 'pi-chevron-circle-right',
    // 'pi-chevron-circle-up',
    // 'pi-circle-off',
    // 'pi-delete-left',
    // 'pi-equals',
    // 'pi-file-check',
    // 'pi-file-edit',
    // 'pi-file-export',
    // 'pi-file-import',
    // 'pi-file-plus',
    // 'pi-file-word',
    // 'pi-file-excel',
    // 'pi-filter-slash',
    // 'pi-flag',
    // 'pi-flag-fill',
    // 'pi-folder-plus',
    // 'pi-hashtag',
    // 'pi-indian-rupee',
    // 'pi-language',
    // 'pi-list-check',
    // 'pi-lock-open',
    // 'pi-mars',
    // 'pi-microsoft',
    // 'pi-percentage',
    // 'pi-prime',
    // 'pi-reddit',
    // 'pi-replay',
    // 'pi-slack',
    // 'pi-sliders-v',
    // 'pi-sort-alpha-alt-down',
    // 'pi-sort-amount-down-alt',
    // 'pi-sort-down',
    // 'pi-sort-up',
    // 'pi-stop-circle',
    // 'pi-tags',
    // 'pi-telegram',
    // 'pi-thumbs-down',
    // 'pi-thumbs-down-fill',
    // 'pi-thumbs-up',
    // 'pi-thumbs-up-fill',
    // 'pi-turkish-lira',
    // 'pi-user-edit',
    // 'pi-user-minus',
    // 'pi-user-plus',
    // 'pi-verified',
    // 'pi-window-maximize',
    // 'pi-window-minimize',
  ];

  filteredPrimeNgIcons: string[] = [];

  constructor() {}

  ngOnInit() {
    this.filterIcons();
  }

  private filterIcons(): void {
    this.filteredPrimeNgIcons = this.rawPrimeNgIcons.filter(
      (icon) => icon !== null && icon !== undefined && icon.trim() !== ''
    );
  }

  show() {
    this.visible = true;
  }

  hide() {
    this.visible = false;
  }

  selectIcon(icon: string) {
    this.iconSelected.emit(icon);
    this.hide();
  }

  cancelSelection() {
    this.hide();
  }
}
